package at.ac.uibk.pm.g06.csaz9837.s05.e03;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class Main {

    public static void main(String[] args) {

        /**
         * The data was generated by a random selection from lists and a match with real
         * persons is purely coincidental.
         */
        String[] csv = {
                "Li Kim,Kranewitterstraße 4;6020;Innsbruck;Austria,09.12.1997,passe-temps:aNT-KEepINg",
                "Nour Vargas,Serlesweg 2;6020;Innsbruck;Austria,22.01.1995,aficiones:SURvIVAlISm;kung Fu;ROBOt cOmbat",
                "Aleksandr Houssein,Seilergasse 6;6020;Innsbruck;Austria,08.04.1999,aficiones:GYmNASTIcs",
                "Jelena Pierre,Josef-Wilberger-Straße 1;6020;Innsbruck;Austria,20.11.1996,passe-temps:rEsEaRch;BUSinESS",
                "Monika Madrid,Lehmweg 3;6020;Innsbruck;Austria,05.01.1993,passe-temps:pRoVErBs;mAgiC;fOsSICkIng",
                "Fatouma Khan,Lutterottistraße 7;6020;Innsbruck;Austria,28.12.1995,passe-temps:meTALwoRKING;reCoRd CoLlecting",
                "Mohamed Rodriguez,Cranachstraße 6;6020;Innsbruck;Austria,03.06.1993,aficiones:MaCrAmE",
                "Md Memmedov,Prinz-Eugen Brücke 10;6020;Innsbruck;Austria,04.07.1991,aficiones:KNoWleDge/wOrd gameS;ENTertaInInG",
                "Dimitris Martin,Gsturnsteig 10;6020;Innsbruck;Austria,21.02.1990,passe-temps:elEctRONIc GAMes;vintAge cArs;HorsEShoeS",
                "Mpho Rusu,Heiligwasserwiese 1;6020;Innsbruck;Austria,02.08.1990,aficiones:CLimbinG;wEIghT trAINInG",
        };

        List<Person> persons = new ArrayList<>();
        String[] csv_split;
        for (int i = 0; i < csv.length; i++) {
            String csv_row = csv[i];
            csv_split = csv_row.split(",");
            String names = csv_split[0];
            String adresses = csv_split[1];
            String birthdays = csv_split[2];
            String hobbies = csv_split[3];

            String[] fullNames = names.split(" ");
            String firstName = fullNames[0];
            String lastName = fullNames[1];

            String[] adressSplitted = adresses.split(";");
            String[] streetAndNumber = adressSplitted[0].split(" ");
            String street;
            String housenumber;
            if (streetAndNumber.length == 3){
                street = streetAndNumber[0] + " " + streetAndNumber[1];
                housenumber = streetAndNumber[2];
            } else {
                street = streetAndNumber[0];
                housenumber = streetAndNumber[1];
            }

            int zipCode = Integer.parseInt(adressSplitted[1]);
            String city = adressSplitted[2];
            String country = adressSplitted[3];

            String[] hobbieList = hobbies.replaceAll("aficiones:","").replaceAll("passe-temps:", "").toLowerCase().split(";");
            Address adress = new Address(street,housenumber,zipCode,city,country);
            Person person = new Person(firstName,lastName,adress,birthdays,hobbieList);
            persons.add(person);
        }

        /**
         * add code here to split the data of each row, such that you can create
         * instances of type Person
         *
         * store the individual instances in the list named persons
         */

        for (int i = 0; i < persons.size(); i++) {
            System.out.println(persons.get(i));
            System.out.println("***********************************************************");
        }

    }
}