CFLAGS = -Wall -Wextra

all: task3_printer task3_printer_server

clean:
	$(RM) task3_printer task3_printer.o
	$(RM) task3_printer_server task3_printer_server.o

task3_printer: task3_printer.o
task3_printer_server: task3_printer_server.o
